# Generated by Django 2.1.5 on 2019-06-14 15:40

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190614_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='正文必须是markdown格式', verbose_name='正文'),
        ),
    ]
