# Generated by Django 2.1.1 on 2019-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190614_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
