# Generated by Django 2.1.5 on 2019-06-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
