# Generated by Django 2.1.5 on 2019-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190607_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='weight',
            field=models.IntegerField(default=100, help_text='权重，决定侧边栏展示的先后顺序，默认为100', verbose_name='权重'),
        ),
    ]
