# Generated by Django 2.1.5 on 2019-06-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_sidebar_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['weight'], 'verbose_name': '侧边栏', 'verbose_name_plural': '侧边栏'},
        ),
        migrations.AddField(
            model_name='sidebar',
            name='class_name',
            field=models.CharField(default='gonggao', max_length=50, verbose_name='类名'),
        ),
    ]
