# Generated by Django 2.1.1 on 2019-07-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20190628_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.TextField(blank=True, help_text='如果设置的不是HTML类型，可为空', verbose_name='内容'),
        ),
    ]
