# Generated by Django 2.1.1 on 2019-08-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0024_auto_20190815_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='回复评论'),
        ),
    ]
