# Generated by Django 2.1.1 on 2019-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('status', models.PositiveIntegerField(choices=[(0, '未激活'), (1, '删除')], default=0, verbose_name='验证')),
                ('send_type', models.CharField(choices=[('register', '邮箱注册'), ('forget', '忘记密码')], max_length=10, verbose_name='发送类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('nick', models.CharField(default='123', max_length=10, verbose_name='昵称')),
                ('question1', models.PositiveIntegerField(choices=[(0, '你的第一辆车？'), (1, '你初中学校的名字？'), (2, '你父亲的生日？'), (3, '你母亲的生日？'), (4, '你宠物的名字？')], verbose_name='密保问题1')),
                ('anwser1', models.CharField(max_length=255, verbose_name='答案1')),
                ('question2', models.PositiveIntegerField(choices=[(0, '你的第一辆车？'), (1, '你初中学校的名字？'), (2, '你父亲的生日？'), (3, '你母亲的生日？'), (4, '你宠物的名字？')], verbose_name='密保问题2')),
                ('anwser2', models.CharField(max_length=255, verbose_name='答案1')),
                ('birthday', models.DateField(auto_now_add=True, null=True, verbose_name='生日')),
                ('status', models.PositiveIntegerField(choices=[(0, '正常'), (1, '审核'), (2, '删除')], default=0, verbose_name='用户状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sex', models.PositiveIntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=3, verbose_name='性别')),
                ('uid', models.CharField(default='u001', max_length=255, verbose_name='用户id')),
                ('isActive', models.IntegerField(default=0, verbose_name='是否激活')),
                ('avatars', models.ImageField(default='avatars/default.png', upload_to='avatars')),
                ('introduction', models.TextField(default="I'm the monster", verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
